### ISSUE TITLE
Is PHP dependency ">=5.4.0" mandatory?

### ISSUE THREAD

**Issue by xmojmr** [milo/github-api#11]
Can I use PHP ">=5.3.29" instead?

[php.net: What has changed in PHP 5.4.x](http://php.net/manual/en/migration54.changes.php) says

> Most improvements in PHP 5.4.x have no impact on existing code. There are a [few incompatibilities](http://php.net/manual/en/migration54.incompatible.php) and [new features](http://php.net/manual/en/migration54.new-features.php) that should be considered, and code should be tested before switching PHP versions in production environments

But I'm not able to review the `github-api` code and check if the _few incompatibilities_ or _new features_ are in use.

Any of `Yes/No/Don't know` answers is good enough for me as I can upgrade to PHP 5.4 I just want to know if it is necessary to undergo the hassle

**Comment by JanTvrdik** [comment]
No, you can not use PHP 5.3.29. PHP 5.4+ is required because short array notation and `$this` in closures is used.

**Comment by xmojmr** [comment]
@JanTvrdik :star2:
