### ISSUE TITLE
Api::decode() fails when parsing result of Request::HEAD request

### ISSUE THREAD

**Issue by xmojmr** [milo/github-api#12]
The function throws "_Decoded JSON is not an array or object._" at https://github.com/milo/github-api/blob/v1.4.0/src/Github/Api.php#L257 because the actual value of `$contents` is `""` and it does not match `is_array()` test neither the `is_object()` test.

I want to issue a `Request::HEAD` - style request and call some generic `GitHub` error handler before running my code. How can I do it? Is behavior of `decode()` designed or it is just a not-yet covered edge case?

Test case:

````
$api = new Github\Api();
$response = $api->head("/users");
$decoded = $api->decode($response);
````

Expected result: `$decoded` contains some empty value
Actual result: exception is thrown

**Comment by milo** [comment]
I'm not sure, this is the accurate behaviour, but the HTTP HEAD method is designed to never return the body contents. It returns only the headers, so I expected noone will decode it but will use only the `$response->getHeader()` and similar.

**Comment by xmojmr** [comment]
I know that there's really nothing useful in the content, I'd like to somehow reuse the generic error handling code in https://github.com/milo/github-api/blob/v1.4.0/src/Github/Api.php#L262-L290 and calling the `Api::decode()` seems to be the only way

**Comment by milo** [comment]
Errors handling part is tightly adherent to [Github API](https://developer.github.com/v3/#client-errors) specification, so `Api::decode()` is really the only place.

Btw. the HTTP part is already extracted to [bitbang/http](https://github.com/bitbang/http). (but the Api part from here is still missing)

**Comment by xmojmr** [comment]
Ok, thanks for explanation. The original reason why I wanted to use the `Request::HEAD`-style queries was to speed-optimize the `CachedClient`. It turned out that I'll need some more changes, e.g. `FileCache` with directory structure similar to "`users/02/02047ca5656be6ac643cb5fcb9de8276d721a08e.php`" to reduce the number of files in one directory.

Knowing that using `Api::decode()` for `Request::HEAD` queries does not make much sense and it is not recommended thing to do, is enough for me to continue.

Once I have some kind of refactored version which works for me ready, may be I'll propose a pull request

**Comment by milo** [comment]
@xmojmr Great. Looking forward.
