### ISSUE TITLE
Fatal error: Class 'Login' not found

### ISSUE THREAD

**Issue by TheZoker** [milo/github-api#15]
Awesome framework!

But I have a issue:
When I try to use `Login::getToken()` I get the error
```
Fatal error: Class 'Login' not found in /helper.php on line 42
```
But I included the class in the helper.php file: 
```
<?php
require_once( 'framework/github-api.php' );
use Milo\Github;
```

**Comment by JanTvrdik** [comment]
You need to use [namespace](http://php.net/namespaces) `Milo\Github\OAuth\Login`.

**Comment by TheZoker** [comment]
Ah ok works :) Thank you!
I now get something like this on var_dump:
![img_2015 09 15_20h45m12s_005_](https://cloud.githubusercontent.com/assets/1368405/9886488/d56eafde-5bea-11e5-8205-a2ed4d0ad224.png)

And when i simple return the token, I don`t get any output.

How can I get the token out of this?

**Comment by JanTvrdik** [comment]
You need to load `github-api.php` (or setup autoloading) before calling `session_start`.

**Comment by TheZoker** [comment]
Yep I`m doing that, otherwise I would not get this response I guess.

**Comment by JanTvrdik** [comment]
No, `__PHP_Incomplete_Class` means that at the time of `session_start` the class `Milo\Github\OAuth\Token` is undefined.

**Comment by TheZoker** [comment]
![img_2015 09 15_20h55m37s_006_](https://cloud.githubusercontent.com/assets/1368405/9886766/3c4e0cc6-5bec-11e5-828d-14d6694767eb.png)
This is my code

**Comment by JanTvrdik** [comment]
Strange. Do you have error_reporting set to E_ALL and enabled display_errors?

**Comment by TheZoker** [comment]
Strange, now I get this error:
![img_2015 09 15_21h09m39s_007_](https://cloud.githubusercontent.com/assets/1368405/9887103/2aa5ce30-5bee-11e5-8144-5d7d185b01b0.png)

**Comment by milo** [comment]
@TheZoker Try to dump the `$_SESSION` content. Isn't there some garbage? If so, clean it somehow.

The library uses `$_SESSION['milo.github-api']`. Isn't touched by another app?

**Comment by TheZoker** [comment]
This is the dump of $_SESSION
![img_2015 09 15_21h14m30s_008_](https://cloud.githubusercontent.com/assets/1368405/9887225/d7a5547a-5bee-11e5-9a43-59b7e8a33a80.png)

**Comment by milo** [comment]
Try `unset($_SESSION['milo.github-api'])` directly after the `session_start()`. Only once and remove it. Then, try whole auth roundtrip again.

**Comment by milo** [comment]
Oh, maybe I got it. Isn't session started somehow earlier? I mean, your `session_start()` in oauth() function is the second one.

**Comment by TheZoker** [comment]
But I dont have any other `session_start()` anywhere else

**Comment by milo** [comment]
Wordpress does not start it? Or maybe PHP's `session.auto_start`? Try `var_dump(session_status());` before the `require_once ...;`

**Comment by TheZoker** [comment]
![img_2015 09 15_21h38m20s_009_](https://cloud.githubusercontent.com/assets/1368405/9887848/2769d4c4-5bf2-11e5-927b-1c1ee4c2fd00.png)
So there is another plugin uses the session

**Comment by milo** [comment]
I see. So, session is somewhere already started before you load the github-api libs. I don't know the Wordpress, maybe there is some hook for plugins to load the libraries first.

If not, you try this nasty hack in [here](https://github.com/milo/github-api/blob/93409cc970ebe892dc0992778f2ba436b8fc246b/src/Github/OAuth/Login.php#L146) and let me know.
```php
public function getToken()
{
	$token = $this->storage->get('auth.token');
	if ($token === NULL) {
		throw new Github\LogicException('Token has not been obtained yet.');
	} elseif ($token instanceof \__PHP_Incomplete_Class) {
		$token = unserialize(serialize($token));
	} 
	return $token;
}
```

**Comment by milo** [comment]
> Btw: How can I open the oauth window in a new window (popup)?

Sorry, that's the frontend thing which I don't solve.

**Comment by TheZoker** [comment]
I can`t test it, because I get this error:
![img_2015 09 15_21h58m30s_011_](https://cloud.githubusercontent.com/assets/1368405/9888376/05299aea-5bf5-11e5-9ac0-ee0b288acb2a.png)

**Comment by milo** [comment]
@TheZoker The error is caused by the Same Origin Policy setting. It is not relevant to this library.

Anyway, I released a new version 1.4.3 where is a token stored as an ordinary array. It prevents `__PHP_Incomplete_Class` error.

**Comment by TheZoker** [comment]
@milo Is there any way to generate and save a state without calling askPermissions() ?

**Comment by milo** [comment]
No, if you need a user's permissions. Btw. why do you access GitHub webpage by AJAX? You need to redirect a browser window. User will click 'Accept' on GitHub web and than will be redirected back to your site.
