### ISSUE TITLE
Personal Access Tokens

### ISSUE THREAD

**Issue by certainlysylvia** [milo/github-api#16]
Possible to use instead of Application Tokens? - I have an app that's inhouse to a private repo and we'd rather use the personal token ..

I had a look through the code and it doesn't appear to be the case - PS: excellent understanding of namespacing and OO ... you would not believe the messes I encountered trying other libs first :)

**Comment by milo** [comment]
Hi! It's possible. ([doc](https://github.com/milo/github-api/wiki/OAuth-token-obtaining)) In a short:
```php
$token = new Milo\Github\OAuth\Token('21r2a12a5as4e65t4654fgsad');
$api = new Milo\Github\Api;
$api->setToken($token);
```

**Comment by milo** [comment]
And now I see, GitHub updates the settings navigation since I wrote the doc. I'll update it.
