### ISSUE TITLE
oAuth fails at second time

### ISSUE THREAD

**Issue by TheZoker** [milo/github-api#17]
I have a issue with oauth.
When I first use it, it works fine. But when I revoke the key and try to get another one, I always get the same key again. And then github returns "401 - Bad credentials" error

When I switch browser, it works fine again, so maybe any kind of session issue.

Is there anyway to fix this?

oAuth function is here: https://github.com/TheZoker/GithubTemp/blob/master/github.php#L85-L118

**Comment by milo** [comment]
It is because the old token is still in session. I'm solving it in application, catching the `Milo\Github\UnauthorizedException` and forcing new token. It looks like:

```php
try {
    $api->decode(...);
} catch (UnauthorizedException $e) {
    Location("....?force=1");
    die();
}
```

```php
# Force new OAuth token
if (isset($_GET['force'])) {
	$login->dropToken();
}

# Token obtaining
if ($login->hasToken()) {
	$token = $login->getToken();
} else {
	if (isset($_GET['back'])) {
		$token = $login->obtainToken($_GET['code'], $_GET['state']);
		header("Location: $appUrl");  # drop the 'code' and 'state' from URL
		die();
	} else {
		# Performs redirect to Github page
		$login->askPermissions("$appUrl?back=1");
	}
}
```

There is no automatic reaction, because it depends on application, how it wants to behave.

The way how to solve it automatically is to register own onResponse() callback like:
```php
$api = new Github\Api;
$api->setToken($token);
$api->getClient()->onResponse(function (Milo\Github\Http\Response $response) use ($appUrl) {
	if ($response->isCode($response::S401_UNAUTHORIZED)) {
		header("Location: $appUrl?force=1");
		die();
	}
});
```

**Comment by TheZoker** [comment]
Works perfectly, thank you!
