### ISSUE TITLE
param replacement no separated by '/' error

### ISSUE THREAD

**Issue by Grummfy** [milo/github-api#21]
Example:
```
$response = $api->get('/repos/:owner/:repo/compare/:base...:head', [
	'owner' => 'atoum',
    'repo' => 'atoum',
    'base' => '3.0.0',
    'head' => '3.1.0',
]);
```
will  provoke an error

> PHP Fatal error:  Uncaught Milo\Github\MissingParameterException: Missing parameter 'base...:head' for URL path '/repos/:owner/:repo/compare/:base...:head'. in /home/jvb/workspace/_perso/atoum-ref/atoum.github.io/scripts/release/vendor/milo/github-api/src/Github/Api.php:373
> Stack trace:
> #0 [internal function]: Milo\Github\Api->Milo\Github\{closure}(Array)
> ...

**Comment by milo** [comment]
Thanks for the report. I'll release new version.

**Comment by Grummfy** [comment]
whaa that's fast! thanks
