### ISSUE TITLE
Need means to supply "$options" parameter when instantiating a client via the Api object

### ISSUE THREAD

**Issue by sbillard** [milo/github-api#35]
I had the need to specify the **CURLOPT_SSL_VERIFYPEER** option to the *CurlClient* instantiation because I am using a self-signed certificate and have not found a way to get CURL/GitHub to be happy with the certificate. My need is to get the file name for the latest release in the repository and I can condition my code to know that it is running in a test environment so I am not too concerned about the issues of the request not being verified.

I have modified *Api::__construct* and the *Helpers::createDefaultClient* functions to pass the *$options* array as an additional parameter and all works well. It would really be nice to have this change incorporated in your released code so I don't have to propagate the change whenever I upgrade to a new release.

A really nice augmentation to this change would be to have an equivalence mapping of these options so that the calling code does not need to be cognisant of whether the curl or stream client is being used.

**Comment by milo** [comment]
Hi Stephen,

I don't want to pollute mentioned methods signature, the `Helpers::createDefaultClient()` is only handy factory. You can pass cURL options via `CurlClient` constructor.

```php
$httpClient = new Milo\Github\Http\CurlClient([CURLOPT_SSL_VERIFYPEER => 0]);
$api = new Milo\Github\Api($httpClient);
```

**Comment by sbillard** [comment]
Thanks. This works for me.
